analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6875
  brandStrength: 0.8684211
  lightness: 0.625
  brandColors:
    - '#ffffff'
    - '#a79376'
    - '#dad2c4'
    - '#271545'
    - '#5c4f72'
  rhythmicContrast: 0.3313641
typography_spectrum: 0.4441461
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.452739
favicon: null
name: traintotransform
