name: traintotransform
favicon: null
layout_spectrum: 0.4583410210907459
typography_spectrum: 0.173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a79376'
    - '#dad2c4'
    - '#271545'
    - '#5c4f72'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
